channel-io/channel-web-sdk-loader

.github/pull_request_template.md, README.md, package-lock.json, package.json, src/index.ts, tsconfig.json
- tsconfig
- package.json
- scope
- keywords
- devDependencies
- commitizen config
- README.md
- pull_request_template.md
- License -> Apache 2.0
- @see https://github.com/channel-io/plugin-web/blob/exp/docs/installation-guide/SPA/ChannelService.ts
- class -> object literal 로 export 방식 수정
- class constructor에서 loader -> 별도 메서드
- nextJS 같이 SSR 환경에서 이슈 존재함
- class constructor함수내에서 sdk를 로딩하고, new Class 를 export하면, 해당 모듈이 evaluate될 때 window가 없어 제대로 동작하지 않을 수 있습니다
- https://github.com/channel-io/plugin-web/blob/exp/docs/installation-guide/SPA/ChannelService.ts
- https://developers.channel.io/docs/web-channelio
=> First setting codebase 

.github/workflows/publish.yml
- ci(github-workflow): add npm publish workflow
- use npm token by github secret
=> ci(github-workflow): add npm publish workflow

.github/workflows/publish.yml, .npmrc
- ci(npmrc): add npmrc for auth config
- NPM_AUTH_TOKEN
=> ci(npmrc): add npmrc for auth config

.github/workflows/publish.yml, .npmrc, package.json
=> ci(workflow): change npm registry & add tsc option -d

package-lock.json, package.json
=> chore(package.json): version 0.2.0

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/pull_request_template.md
- docs(github template): add issue_template
- fix pull_request_template
=> docs(github template): add issue_template

README.md, package.json, src/index.ts
- Change how to import SDK
- Fix README.md
- Fix init method name -> loadScript
- Change package.json
```typescript
// as-is
import ChannelService from '@channel-io/channel-web-sdk-loader'
// to-be
import * as ChannelService from '@channel-io/channel-web-sdk-loader'
```
```typescript
// as-is
ChannelService.init()
// to-be
ChannelService.loadScript()
```
=> Fix!: Add annotation & change import way

.gitignore, README.md, package-lock.json, package.json, src/index.ts
- install typedoc package for dev
- export interface and type for typedoc
- change bootOption.language type
- `string` -> `'en'|'ko'|'ja'`
=> refactor: add annotation to interface and type

.github/workflows/generate-and-deploy-typedoc.yml
- ci(github-workflows): add workflow 'generate-and-deploy-typedoc'
- publish_dir: docs
=> ci(github-workflows): add workflow 'generate-and-deploy-typedoc'

README.md
=> Docs(readme): link typedoc

src/index.ts
- refactor(loadscript): remove minify & add annotation
- annoation for not supporting SSR (only on browser)
=> refactor(loadscript): remove minify & add annotation

README.md, src/index.ts
- readme
- warning for using the sdk on client-side only
- ChannelIO methods
- add safeguard for ssr
=> Enhances: add safeguard for SSR environments

README.md
- add badges to readme.md
- npm package version
- npm package license
- npm package download per month
=> docs(readme):add badges

README.md
=> docs(readme): fix wrong path & description for getting plugin key

src/index.ts
- chore(method-annotation): fix annotation for right references
- No
- @see https://desk.channel.io/root/threads/groups/WebCellFront-115250/6513f80cd93ede69e599/651e4744808d40d43648
=> chore(method-annotation): fix annotation for right references

package-lock.json, package.json
- add korean keywords for package
- keywords
- 채널톡
- 채널
- version change
-  v0.4.3 -> v1.0.0
- No
=> Chore: add korean keywords for package

package-lock.json, package.json, src/index.ts
- add openSupportbot API
- package versions -> v1.1.0
- add openSupportbot API
- add annotation
- Improve openChat annotations
- No
- https://developers.channel.io/docs/web-channelio#opensupportbot
=> Feat: add openSupportbot API

LICENSE
- chore(license): add missing copyright owners
- 2023 Channel Corp.
- No
- https://github.com/channel-io/bezier-react/blob/main/LICENSE
=> chore(license): add missing copyright owners

README.md
- chore(readme): add badge to readme
- add link
- add minzip badge
- No
=> chore(readme): add badge to readme

README.md
- add Installation commands for Yarn & PNPM
- No
=> docs(readme): add Installation commands for Yarn & PNPM

README.md, package-lock.json, package.json
=> Fix: change how to specifying the theme an logo is shown to

package.json
=> chore(package.json): add crm keyword to package.json
